package com.github.codeteapot.jmibeans;

import com.github.codeteapot.jmibeans.machine.MachineRef;
import java.util.Optional;
import java.util.stream.Stream;

/**
 * Access to the context generated by the platform adapter.
 *
 * <p>It allows interacting with the available machines.
 *
 * @see PlatformAdapter#getContext()
 */
public interface PlatformContext {

  /**
   * All available machines on the platform.
   *
   * @return The stream of all machines.
   */
  Stream<Machine> available();

  /**
   * The machine identified by the specified reference, if available.
   *
   * @param ref The reference of the requested machine.
   *
   * @return The machine identified by the given reference, or empty if it is not available.
   */
  Optional<Machine> lookup(MachineRef ref);
}
