package com.github.codeteapot.jmibeans.event;

import static java.util.Objects.requireNonNull;

import com.github.codeteapot.jmibeans.machine.MachineRef;
import java.util.EventObject;

/**
 * Base class for all machine events.
 *
 * <p>All specialization includes the reference of the machine involved.
 */
public abstract class MachineEvent extends EventObject {

  private static final long serialVersionUID = 1L;

  /**
   * Reference of the related machine.
   */
  private final MachineRef machineRef;

  /**
   * Constructs an event generated by the specified source and with the reference of the involved
   * machine.
   *
   * @param source The object that generated the event.
   * @param machineRef The reference of the involved machine.
   */
  protected MachineEvent(Object source, MachineRef machineRef) {
    super(source);
    this.machineRef = requireNonNull(machineRef);
  }

  /**
   * The reference of the involved machine.
   *
   * @return The reference.
   */
  public MachineRef getMachineRef() {
    return machineRef;
  }
}
